
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LOAD MODEL NEGATIVE NEUTRAL POSITIVE SAVE VECTORcommand : LOAD VECTOR\n               | SAVE VECTOR\n               | LOAD MODEL\n               | SAVE MODEL\n               | sentimentsentiment : POSITIVE\n                 | NEGATIVE\n                 | NEUTRAL'
    
_lr_action_items = {'LOAD':([0,],[2,]),'SAVE':([0,],[3,]),'POSITIVE':([0,],[5,]),'NEGATIVE':([0,],[6,]),'NEUTRAL':([0,],[7,]),'$end':([1,4,5,6,7,8,9,10,11,],[0,-5,-6,-7,-8,-1,-3,-2,-4,]),'VECTOR':([2,3,],[8,10,]),'MODEL':([2,3,],[9,11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'sentiment':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> LOAD VECTOR','command',2,'p_command','parser.py',5),
  ('command -> SAVE VECTOR','command',2,'p_command','parser.py',6),
  ('command -> LOAD MODEL','command',2,'p_command','parser.py',7),
  ('command -> SAVE MODEL','command',2,'p_command','parser.py',8),
  ('command -> sentiment','command',1,'p_command','parser.py',9),
  ('sentiment -> POSITIVE','sentiment',1,'p_sentiment','parser.py',16),
  ('sentiment -> NEGATIVE','sentiment',1,'p_sentiment','parser.py',17),
  ('sentiment -> NEUTRAL','sentiment',1,'p_sentiment','parser.py',18),
]
